### ISSUE TITLE
2020.11.16

### ISSUE THREAD

**Issue by matry-ny** [LazarevAndrew22/HomeWork#4]
немного не то
нужно жонглировать объектами
1. создать объект ментора
2. создать объект студента
3. в объекте ментора создавать объект задания и передавать в объект студента
4. в объекте студента выполняем задание и передаем объект задания обратно в объект ментора
5. в объекте ментора проверяем задание и закрываем его

**Comment by LazarevAndrew22** [comment]
fixed
